/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author sorindoc
 */
public enum Message {
		AFFICHER_DEMANDE_ACHETER_PROPRIETE,
		AFFICHER_ACHAT_PROPRIETE,

		AFFICHER_ACHAT_BATIMENT,
		AFFICHER_PROPRIETE_CONSTRUCTIBLE,
		
		AFFICHER_PAYER_LOYER,
		AFFICHER_PAYER_TAXE,
		
		AFFICHER_CARTE_CAISSE_DE_COMMUNAUTE,
		AFFICHER_CARTE_CHANCE,
		
		AFFICHER_PASSAGE_DEPART,
		AFFICHER_ARGENT_RESTANT,
		
		AFFICHER_CARREAU,
	
		AFFICHER_FIN_PARTIE,
		
		AFFICHER_JOUEUR,
		AFFICHER_JOUEUR_ELIMINE,
		
		AFFICHER_FAIT_UN_DOUBLE,
		AFFICHER_3D_DOUBLE,
		
		AFFICHER_ATTENDRE_PROCHAIN_TOUR,
		
		AFFICHER_PATRIMOINE,
		AFFICHER_LANCER_DES,
		
		AFFICHER_MENU,
		
		AFFICHER_INTERACTION_PRISON,
		AFFICHER_LIBERE_PRISON,
		AFFICHER_DERNIER_TOUR_EN_PRISON,
		
		AFFICHER_PAS_DE_TERRAIN_CONSTRUCTIBLE,
		AFFICHER_PAS_ASSEZ_DE_BATIMENTS,
		
		AFFICHER_PAS_ASSEZ_DARGENT,
		
		AFFICHER_SORTIE_PRISON_AMANDE,
		AFFICHER_SORTIE_PRISON_DOUBLE
}
